import { optionsType, ProductType } from "@/types";
import { BellRing, Globe, Heart, ImageDown, Package } from "lucide-react";

export const Nav_Link = [
  {
    name: "home",
    path: "",
    icon: "home",
  },
  {
    name: "categories",
    path: "/categories",
    icon: "shopping-cart",
  },
  {
    name: "auction",
    path: "/auction",
    icon: "info-circle",
  },
  {
    name: "ads",
    path: "/ads",
    icon: "Megaphone",
  },
];

export const Nav_Icons = [
  { name: "MyAdvertensies", Icon: ImageDown, path: "/myAdvertensies" },
  { name: "Packages", Icon: Package, path: "/packages" },
  { name: "MyFavorites", Icon: Heart, path: "/favorites" },
  { name: "Notification", Icon: BellRing, path: "/notifications" },
  {
    name: "Language",
    Icon: Globe,
    path: "/",
    languages: [
      { code: "en", label: "English" },
      { code: "ar", label: "العربية" },
    ],
  },
];

export const Banners = [
  {
    title: "خصم 30%",
    description: " عرض عنوان المنتج",
    image: "/Banner/hero-cat.png",
    btnTitle: "عرض الآن",
    path: "/",
  },
  {
    title: "خصم 50%",
    description: "عرض عنوان المنتج",
    image: "/Banner/manBanner.png",
    btnTitle: "عرض الآن",
    path: "/",
  },
  {
    title: "خصم 30%",
    description: " عرض عنوان المنتج",
    image: "/Banner/womanBanner.png",
    btnTitle: "عرض الآن",
    path: "/",
  },
  {
    title: "خصم 30%",
    description: " عرض عنوان المنتج",
    image: "/Banner/furniture.png",
    btnTitle: "عرض الآن",
    path: "/",
  },
];

export const Categories = [
  {
    name: "Home-furniture",
    path: "/Home-furniture",
    icon: "/categories/أثاث منزلي.svg",
  },
  {
    name: "Electronics",
    path: "/Electronics",
    icon: "/categories/أجهزة إلكترونية.svg",
  },
  {
    name: "Players",
    path: "/Players",
    icon: "/categories/ألعاب وتسلية.svg",
  },
  {
    name: "Shelters",
    path: "/Shelters",
    icon: "/categories/تحف نادرة.svg",
  },
  {
    name: "Words-and-Functions",
    path: "/Words-and-Functions",
    icon: "/categories/حرف ووظائف.svg",
  },
  {
    name: "Social-Accounts",
    path: "/Social-Accounts",
    icon: "/categories/حسابات التواصل.svg",
  },
  {
    name: "Motorcycles",
    path: "/Motorcycles",
    icon: "/categories/دراجات نارية.svg",
  },
  {
    name: "Cars",
    path: "/Cars",
    icon: "/categories/سيارات ودراجات.svg",
  },
  {
    name: "Buildings",
    path: "/Buildings",
    icon: "/categories/عقارات.svg",
  },
  {
    name: "Construction",
    path: "/Construction",
    icon: "/categories/مقاولات.svg",
  },
  {
    name: "Children's",
    path: "/Children's",
    icon: "/categories/مستلزمات اطفال.svg",
  },
  {
    name: "Men's",
    path: "/Men's",
    icon: "/categories/مستلزمات رجال.svg",
  },
  {
    name: "Women's",
    path: "/Women's",
    icon: "/categories/مستلزمات نسائية.svg",
  },
  {
    name: "Healthcare",
    path: "/Healthcare",
    icon: "/categories/مستلزمات طبية.svg",
  },
];

export const Products: ProductType[] = [
  {
    id: 1,
    name: "Red-Bag",
    price: "50",
    main_image: "/products/bag.png",
    city: {
      id: 1,
      name: "محافظة الجهراء",
      name_ar: "محافظة الجهراء",
      name_en: "Al Jahra",
    },
    category: {
      id: 1,
      name: "مستلزمات نسائية",
      name_en: "Women's Accessories",
      image: "/products/bag.png",
    },
    sub_category: {
      id: 1,
      name: "حقائب",
      name_en: "Bags",
      image: "/products/bag.png",
    },
    images: ["/products/bag.png"],
    type: "auction",
    condition: "new",
    communication_methods: ["phone"],
    description: "Description for Red Bag",
    views_count: 10,
    created_at: "2025-11-23T11:10:06.000Z",
    updated_at: "2025-11-23T11:10:06.000Z",
    user: {
      id: 1,
      name: "Seller Name",
      email: "seller@example.com",
      image: "/products/bag.png",
      phone: "123456789",
    },
    display_price: "50",
    is_active: true,
    is_auction: true,
    is_featured: false,
    is_owner: false,
    notes: "",
  },
  {
    id: 2,
    name: "Makeup",
    price: "120",
    main_image: "/products/makeup.png",
    city: {
      id: 2,
      name: "محافظة الأحمدي",
      name_ar: "محافظة الأحمدي",
      name_en: "Al Ahmadi",
    },
    category: {
      id: 1,
      name: "مستلزمات نسائية",
      name_en: "Women's Accessories",
      image: "/products/makeup.png",
    },
    sub_category: {
      id: 2,
      name: "مكياج",
      name_en: "Makeup",
      image: "/products/makeup.png",
    },
    images: ["/products/makeup.png"],
    type: "auction",
    condition: "new",
    communication_methods: ["phone"],
    description: "Description for Makeup",
    views_count: 15,
    created_at: "2025-11-23T11:10:06.000Z",
    updated_at: "2025-11-23T11:10:06.000Z",
    user: {
      id: 1,
      name: "Seller Name",
      email: "seller@example.com",
      image: "/products/makeup.png",
      phone: "123456789",
    },
    display_price: "120",
    is_active: true,
    is_auction: true,
    is_featured: false,
    is_owner: false,
    notes: "",
  },
  {
    id: 3,
    name: "Red-Bag",
    price: "50",
    main_image: "/products/bag.png",
    city: {
      id: 1,
      name: "الرياض",
      name_ar: "الرياض",
      name_en: "Riyadh",
    },
    category: {
      id: 1,
      name: "الرياض",
      image: "/products/bag.png",
      name_en: "Riyadh",
    },
    images: ["/products/bag.png", "/products/makeup.png"],
    type: "auction",
    condition: "new",
    communication_methods: ["phone", "whatsapp"],
    description: "",
    views_count: 10,
    created_at: "2025-11-23T11:10:06.000Z",
    updated_at: "2025-11-23T11:10:06.000Z",
    user: {
      id: 1,
      name: "John Doe",
      image: "/products/bag.png",
      email: "john.doe@example.com",
      phone: "123456789",
    },
    display_price: "50",
    is_active: true,
    is_auction: true,
    is_featured: true,
    is_owner: true,
    notes: "",
    sub_category: {
      id: 1,
      name: "الرياض",
      image: "/products/bag.png",
      name_en: "Riyadh",
    },
  },
  {
    id: 4,
    name: "Makeup",
    price: "120",
    main_image: "/products/makeup.png",
    city: {
      id: 2,
      name: "محافظة الأحمدي",
      name_ar: "محافظة الأحمدي",
      name_en: "Al Ahmadi",
    },
    category: {
      id: 1,
      name: "مستلزمات نسائية",
      name_en: "Women's Accessories",
      image: "/products/makeup.png",
    },
    sub_category: {
      id: 2,
      name: "مكياج",
      name_en: "Makeup",
      image: "/products/makeup.png",
    },
    images: ["/products/makeup.png"],
    type: "auction",
    condition: "new",
    communication_methods: ["phone"],
    description: "Description for Makeup",
    views_count: 15,
    created_at: "2025-11-23T11:10:06.000Z",
    updated_at: "2025-11-23T11:10:06.000Z",
    user: {
      id: 1,
      name: "Seller Name",
      email: "seller@example.com",
      image: "/products/makeup.png",
      phone: "123456789",
    },
    display_price: "120",
    is_active: true,
    is_auction: true,
    is_featured: false,
    is_owner: false,
    notes: "",
  },
];

export const ProductsAuction: ProductType[] = [
  {
    id: 1,
    name: "Red-Bag",
    price: "50",
    main_image: "/products/bag.png",
    city: {
      id: 1,
      name: "محافظة الجهراء",
      name_ar: "محافظة الجهراء",
      name_en: "Al Jahra",
    },
    category: {
      id: 1,
      name: "مستلزمات نسائية",
      name_en: "Women's Accessories",
      image: "/products/bag.png",
    },
    sub_category: {
      id: 1,
      name: "حقائب",
      name_en: "Bags",
      image: "/products/bag.png",
    },
    images: ["/products/bag.png"],
    type: "auction",
    condition: "new",
    communication_methods: ["phone"],
    description: "Description for Red Bag",
    views_count: 10,
    created_at: "2025-11-23T11:10:06.000Z",
    updated_at: "2025-11-23T11:10:06.000Z",
    user: {
      id: 1,
      name: "Seller Name",
      email: "seller@example.com",
      image: "/products/bag.png",
      phone: "123456789",
    },
    display_price: "50",
    is_active: true,
    is_auction: true,
    is_featured: false,
    is_owner: false,
    notes: "",
  },
  {
    id: 2,
    name: "Makeup",
    price: "120",
    main_image: "/products/makeup.png",
    city: {
      id: 2,
      name: "محافظة الأحمدي",
      name_ar: "محافظة الأحمدي",
      name_en: "Al Ahmadi",
    },
    category: {
      id: 1,
      name: "مستلزمات نسائية",
      name_en: "Women's Accessories",
      image: "/products/makeup.png",
    },
    sub_category: {
      id: 2,
      name: "مكياج",
      name_en: "Makeup",
      image: "/products/makeup.png",
    },
    images: ["/products/makeup.png"],
    type: "auction",
    condition: "new",
    communication_methods: ["phone"],
    description: "Description for Makeup",
    views_count: 15,
    created_at: "2025-11-23T11:10:06.000Z",
    updated_at: "2025-11-23T11:10:06.000Z",
    user: {
      id: 1,
      name: "Seller Name",
      email: "seller@example.com",
      image: "/products/makeup.png",
      phone: "123456789",
    },
    display_price: "120",
    is_active: true,
    is_auction: true,
    is_featured: false,
    is_owner: false,
    notes: "",
  },
  {
    id: 3,
    name: "Red-Bag",
    price: "50",
    main_image: "/products/bag.png",
    city: {
      id: 1,
      name: "الرياض",
      name_ar: "الرياض",
      name_en: "Riyadh",
    },
    category: {
      id: 1,
      name: "الرياض",
      image: "/products/bag.png",
      name_en: "Riyadh",
    },
    images: ["/products/bag.png", "/products/makeup.png"],
    type: "auction",
    condition: "new",
    communication_methods: ["phone", "whatsapp"],
    description: "",
    views_count: 10,
    created_at: "2025-11-23T11:10:06.000Z",
    updated_at: "2025-11-23T11:10:06.000Z",
    user: {
      id: 1,
      name: "John Doe",
      image: "/products/bag.png",
      email: "john.doe@example.com",
      phone: "123456789",
    },
    display_price: "50",
    is_active: true,
    is_auction: true,
    is_featured: true,
    is_owner: true,
    notes: "",
    sub_category: {
      id: 1,
      name: "الرياض",
      image: "/products/bag.png",
      name_en: "Riyadh",
    },
  },
  {
    id: 4,
    name: "Makeup",
    price: "120",
    main_image: "/products/makeup.png",
    city: {
      id: 2,
      name: "محافظة الأحمدي",
      name_ar: "محافظة الأحمدي",
      name_en: "Al Ahmadi",
    },
    category: {
      id: 1,
      name: "مستلزمات نسائية",
      name_en: "Women's Accessories",
      image: "/products/makeup.png",
    },
    sub_category: {
      id: 2,
      name: "مكياج",
      name_en: "Makeup",
      image: "/products/makeup.png",
    },
    images: ["/products/makeup.png"],
    type: "auction",
    condition: "new",
    communication_methods: ["phone"],
    description: "Description for Makeup",
    views_count: 15,
    created_at: "2025-11-23T11:10:06.000Z",
    updated_at: "2025-11-23T11:10:06.000Z",
    user: {
      id: 1,
      name: "Seller Name",
      email: "seller@example.com",
      image: "/products/makeup.png",
      phone: "123456789",
    },
    display_price: "120",
    is_active: true,
    is_auction: true,
    is_featured: false,
    is_owner: false,
    notes: "",
  },
];

export const Nationality = [
  {
    value: "saudi",
    label: "سعودي",
  },
  {
    value: "egyptian",
    label: "مصري",
  },
  {
    value: "emirati",
    label: "إماراتي",
  },
  {
    value: "jordanian",
    label: "أردني",
  },
  {
    value: "lebanese",
    label: "لبناني",
  },
];

export const Packages = [
  {
    id: 1,
    name: "الباقة الأولى",
    description: "باقة خمس اعلانات",
    price: 500,
    isSpacial: false,
    offerPrice: 20,
  },
  {
    id: 2,
    name: "الباقة الثانية",
    description: "باقة عشرة اعلانات",
    price: 700,
    isSpacial: true,
    offerPrice: 20,
  },
  {
    id: 3,
    name: "الباقة الثالثة",
    description: "باقة عشرين اعلان",
    price: 1000,
    isSpacial: true,
    offerPrice: 20,
  },
  {
    id: 4,
    name: "الباقة الرابعة",
    description: "باقة الخامس وعشرون اعلان",
    price: 1500,
    isSpacial: true,
    offerPrice: 20,
  },
];

export const UserMenu = [
  {
    name: "portfolio",
    icon: "/Icons/portfolio.svg",
    path: "/account",
  },
  {
    name: "advertise",
    icon: "/Icons/advertise.svg",
    path: "/myAdvertensies",
  },
  {
    name: "packages",
    icon: "/Icons/package.svg",
    path: "/packages",
  },
  {
    name: "language",
    icon: "/Icons/language.svg",
    languages: [
      { code: "en", label: "English" },
      { code: "ar", label: "العربية" },
    ],
  },
  {
    name: "privacy",
    icon: "/Icons/privacy.svg",
    path: "/privacy&policies",
  },
  {
    name: "downloadApp",
    icon: "/Icons/download.svg",
    path: "/download-app",
  },
  {
    name: "support",
    icon: "/Icons/support.svg",
    path: "/account",
  },
  {
    name: "logOut",
    icon: "/Icons/logout.svg",
  },
];

export const UserPackagesList = [
  {
    packageID: "الباقة الأولى",
    packageName: "باقة خمس اعلانات",
    packageType: "yearly",
    packageStatus: "active",
    advertisementsRemaining: 5,
    advertisementsTotal: 10,
    packageDate: "4/12/2024",
    packageExpiryDate: "4/12/2025",
  },
  {
    packageID: "الباقة الثانية",
    packageName: "باقة عشر اعلانات",
    packageType: "yearly",
    packageStatus: "active",
    advertisementsRemaining: 5,
    advertisementsTotal: 10,
    packageDate: "4/12/2024",
    packageExpiryDate: "4/12/2025",
  },
];

export const StateProductOptions: optionsType[] = [
  {
    id: "new",
    label: "New",
    value: "new",
  },
  {
    id: "used",
    label: "Used",
    value: "used",
  },
];

export const Product = {
  name: "Premium Wireless Headphones",
  price: 299,
  originalPrice: 399,
  rating: 4.8,
  reviewCount: 2847,
  inStock: true,
  stockCount: 23,
  description:
    "Experience crystal-clear audio with our premium wireless headphones. Featuring advanced noise cancellation technology, 30-hour battery life, and premium comfort design.",
  features: [
    "Active Noise Cancellation",
    "30-hour Battery Life",
    "Premium Comfort Design",
    "Wireless Charging Case",
    "Hi-Res Audio Support",
    "Voice Assistant Compatible",
  ],
  sizes: ["S", "M", "L", "XL"],
  colors: ["Black", "White", "Blue", "Rose Gold"],
  productImages: [
    "/products/product1.jpg",
    "/products/product2.jpg",
    "/products/product3.jpg",
    "/products/product4.jpg",
  ],
  seller: {
    name: "TechStore Pro",
    avatar: "/placeholder.svg?height=60&width=60&text=TS",
    rating: 4.9,
    reviewCount: 15420,
    responseTime: "Within 2 hours",
    location: "New York, USA",
    verified: true,
  },
  similarProducts: [
    {
      id: 1,
      name: "Red-Bag",
      price: 50,
      image: "/products/bag.png",
      location: "محافظة الجهراء",
      offerPrice: "أقل من 90 دينار",
      offerTitle: "مستلزمات نسائية",
    },
    {
      id: 2,
      name: "Makeup",
      price: 120,
      image: "/products/makeup.png",
      location: "محافظة الأحمدي",
      offerPrice: "أقل من 90 دينار",
      offerTitle: "مستلزمات نسائية",
    },
    {
      id: 3,
      name: "Red-Bag",
      price: 50,
      image: "/products/bag.png",
      location: "محافظة الجهراء",
      offerPrice: "أقل من 90 دينار",
      offerTitle: "مستلزمات نسائية",
    },
    {
      id: 4,
      name: "Makeup",
      price: 120,
      image: "/products/makeup.png",
      location: "محافظة الأحمدي",
      offerPrice: "أقل من 90 دينار",
      offerTitle: "مستلزمات نسائية",
    },
  ],
};
